project_id = "zrsdcbqqeyoipzjlasjv"

[functions.generate-qr]
verify_jwt = true

[functions.scan-qr]  
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.release-payment]
verify_jwt = true

[functions.translate-content]
verify_jwt = true