// RPC (Remote Procedure Call) types for Supabase functions
// This file is automatically generated - do not edit manually

import type { Database } from './database'

export type RpcFunctions = Database['public']['Functions']

// Helper type for function parameters
export type FunctionArgs<T extends keyof RpcFunctions> = RpcFunctions[T]['Args']

// Helper type for function return types
export type FunctionReturns<T extends keyof RpcFunctions> = RpcFunctions[T]['Returns']

// Common RPC response wrapper
export interface RpcResponse<T = unknown> {
  data: T | null
  error: string | null
  success: boolean
}

// Edge function response type
export interface EdgeFunctionResponse<T = unknown> {
  data?: T
  error?: string
  status: number
  message?: string
}